module OpenTok.Types where

-- | An OpenTok API key (i.e. project key)
type APIKey = String

-- | An OpenTok API secret (i.e. project secret)
type APISecret = String

-- | An OpenTok Session identifier
type SessionId = String

-- | An OpenTok Archive identifier
type ArchiveId = String

-- | An IPv4 Address
type IPAddress = String

-- | An access token for an OpenTok Session
type Token = String

-- | An error generated by the OpenTok SDK
type OTError = String
