{-# LANGUAGE OverloadedStrings #-}

module OpenTok.Types where

import           Data.Aeson
import           Data.Aeson.Types

-- | An OpenTok API key (i.e. project key)
type APIKey = String

-- | An OpenTok API secret (i.e. project secret)
type APISecret = String

-- | An OpenTok Session identifier
type SessionId = String

-- | An OpenTok Archive identifier
type ArchiveId = String

-- | An IPv4 Address
type IPAddress = String

-- | An access token for an OpenTok Session
type Token = String

-- | An error generated by the OpenTok SDK
type OTError = String

-- | SD (Standard Definition 640 x 480)
--
-- HD (High Definition 1280 x 720)
--
data Resolution = SD | HD

instance Show Resolution where
  show SD = "640x480 (SD)"
  show HD = "1280x720 (HD)"

instance ToJSON Resolution where
  toJSON SD = String "640x480"
  toJSON HD = String "1280x720"

instance FromJSON Resolution where
  parseJSON (String s) = case s of
    "640x480" -> pure SD
    "1280x720" -> pure HD
    _ -> typeMismatch "Could not parse ArchiveResolution" (String s)
  parseJSON x = typeMismatch "Expected String" x
